version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout
      
      - run:
          name: List files
          command: |
            bundle --version      
      
      - run:
          name: List files
          command: |
            ls > file-list.txt

      - store_artifacts:
          path: file-list.txt
