version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout
      
      - run:
          name: Install Jekyll dependencies
          command: |
            bundle --path vendor/bundle

      - run:
          name: Create Static Webpage with Jekyll
          command: |
            bundle exec jekyll build --config _config.yml,_config_prs.yml

      - store_artifacts:
          path: _site
          destination: site
